[package]
name = "shulsaga"
version = "0.1.0"
authors = ["lemonhx <lemonhx@lemonhx.tech>"]
edition = "2018"

[lib]
name = "libshulsaga"
path = "src/lib.rs"

[[bin]]
name = "shulsaga_cli"
path = "src/main.rs"


[dependencies]
enum_dispatch = "0.3"