[package]
name = "renderer_001"
version = "0.1.0"
authors = ["lemonhx <lemonhx@lemonhx.tech>"]
edition = "2018"

[lib]
name = "librenderer_001"
path = "src/lib.rs"

[[bin]]
name = "renderer_001_cli"
path = "src/main.rs"


[dependencies]
enum_dispatch = "0.3"